/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jframe.events;

import java.awt.Color;
import java.awt.event.MouseEvent;

/**
 *
 * @author Elif Eftelya
 */
public class Event_4 extends javax.swing.JFrame {
    
    Color kirmizi=new Color(255,0,0);
    Color yesil=new Color(0,255,0);
    Color mavi=new Color(0,0,255);
    

    /**
     * Creates new form Event_4
     */
    public Event_4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Turuncu = new javax.swing.JPanel();
        jPanel_Mor = new javax.swing.JPanel();
        jPanel_Turkuaz = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_Turuncu.setBackground(new java.awt.Color(242, 196, 138));
        jPanel_Turuncu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_TuruncuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_TuruncuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_TuruncuLayout = new javax.swing.GroupLayout(jPanel_Turuncu);
        jPanel_Turuncu.setLayout(jPanel_TuruncuLayout);
        jPanel_TuruncuLayout.setHorizontalGroup(
            jPanel_TuruncuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );
        jPanel_TuruncuLayout.setVerticalGroup(
            jPanel_TuruncuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );

        jPanel_Mor.setBackground(new java.awt.Color(201, 205, 214));
        jPanel_Mor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_MorMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel_MorMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel_MorLayout = new javax.swing.GroupLayout(jPanel_Mor);
        jPanel_Mor.setLayout(jPanel_MorLayout);
        jPanel_MorLayout.setHorizontalGroup(
            jPanel_MorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );
        jPanel_MorLayout.setVerticalGroup(
            jPanel_MorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel_Turkuaz.setBackground(new java.awt.Color(201, 218, 220));
        jPanel_Turkuaz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_TurkuazMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_TurkuazLayout = new javax.swing.GroupLayout(jPanel_Turkuaz);
        jPanel_Turkuaz.setLayout(jPanel_TurkuazLayout);
        jPanel_TurkuazLayout.setHorizontalGroup(
            jPanel_TurkuazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );
        jPanel_TurkuazLayout.setVerticalGroup(
            jPanel_TurkuazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_Turuncu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel_Mor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel_Turkuaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Turuncu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Mor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Turkuaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel_TuruncuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_TuruncuMouseEntered
       
        jPanel_Turuncu.setBackground(kirmizi);
    }//GEN-LAST:event_jPanel_TuruncuMouseEntered

    private void jPanel_TuruncuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_TuruncuMouseExited
        jPanel_Turuncu.setBackground(mavi);
    }//GEN-LAST:event_jPanel_TuruncuMouseExited

    private void jPanel_MorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_MorMousePressed
        jPanel_Mor.setBackground(yesil);
    }//GEN-LAST:event_jPanel_MorMousePressed

    private void jPanel_MorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_MorMouseReleased
        jPanel_Mor.setBackground(kirmizi);
    }//GEN-LAST:event_jPanel_MorMouseReleased

    private void jPanel_TurkuazMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_TurkuazMouseClicked
        if (evt.getModifiers() == MouseEvent.BUTTON1_MASK) {
            jPanel_Turkuaz.setBackground(yesil);
            
        } else if(evt.getModifiers() == MouseEvent.BUTTON3_MASK) {
            jPanel_Turkuaz.setBackground(Color.MAGENTA);
        }
    }//GEN-LAST:event_jPanel_TurkuazMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Event_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Event_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Event_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Event_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Event_4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel_Mor;
    private javax.swing.JPanel jPanel_Turkuaz;
    private javax.swing.JPanel jPanel_Turuncu;
    // End of variables declaration//GEN-END:variables
}
