/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jframe.events;

import java.awt.Font;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Elif Eftelya
 */
public class Event_5 extends javax.swing.JFrame {

    /**
     * Creates new form Event_5
     */
    public Event_5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Merhaba = new javax.swing.JLabel();
        jButton_Giris = new javax.swing.JButton();
        jTextField_TextAlani = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jLabel_Merhaba.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Merhaba.setText("Merhaba");

        jButton_Giris.setText("Giriş");
        jButton_Giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GirisActionPerformed(evt);
            }
        });

        jTextField_TextAlani.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_TextAlaniKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel_Merhaba, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Giris, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_TextAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jTextField_TextAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton_Giris, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel_Merhaba, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized

        Integer genislik = Event_5.this.getWidth();
        System.out.println("Ekran Genişliği: " + genislik);
        if (genislik > 540) {
            jTextField_TextAlani.setFont(new Font("Arial", Font.BOLD, 24));
            jLabel_Merhaba.setFont(new Font("Arial", Font.BOLD, 24));
            jButton_Giris.setFont(new Font("Arial", Font.BOLD, 24));

        } else {
            jTextField_TextAlani.setFont(new Font("Arial", Font.BOLD, 12));
            jLabel_Merhaba.setFont(new Font("Arial", Font.BOLD, 12));
            jButton_Giris.setFont(new Font("Arial", Font.BOLD, 12));
        }
    }//GEN-LAST:event_formComponentResized

    private void jButton_GirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GirisActionPerformed
        System.out.println("Merhaba");
        JOptionPane.showMessageDialog(this, "merhaba", "Başlık", 1);
    }//GEN-LAST:event_jButton_GirisActionPerformed

    private void jTextField_TextAlaniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_TextAlaniKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            jButton_Giris.doClick();
            
        } else {
        }
        
    }//GEN-LAST:event_jTextField_TextAlaniKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Event_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Event_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Event_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Event_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Event_5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Giris;
    private javax.swing.JLabel jLabel_Merhaba;
    private javax.swing.JTextField jTextField_TextAlani;
    // End of variables declaration//GEN-END:variables
}
